# Generated by Django 6.0.5 on 2026-05-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '货物类别',
                'verbose_name_plural': '货物类别',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除')], max_length=10, verbose_name='操作类型')),
                ('model_name', models.CharField(max_length=30, verbose_name='操作对象')),
                ('object_name', models.CharField(max_length=100, verbose_name='对象名称')),
                ('description', models.CharField(max_length=200, verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
            },
        ),
        migrations.CreateModel(
            name='OrderTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('customer_name', models.CharField(max_length=30, verbose_name='客户名称')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('shipping', '运输中'), ('delivered', '已签收'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order_tb01',
            },
        ),
        migrations.CreateModel(
            name='GoodsTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='货物名称')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量(kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元)')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.goodscategory', verbose_name='货物类别')),
            ],
            options={
                'verbose_name': '货物信息',
                'verbose_name_plural': '货物信息',
                'db_table': 'goods_tb01',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元)')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.goodstb', verbose_name='货物')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.ordertb', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_item',
            },
        ),
    ]
